### ISSUE TITLE
Migrate examples

### ISSUE THREAD

**Issue by bananaappletw** [bananaappletw/koa2-examples#1]
Migrate examples from https://github.com/koajs/examples
- [x] 404
- [x] base-auth
- [x] blog
- [x] body-parsing
- [x] compose 
- [x] conditional-middleware
- [x] cookies
- [x] csrf
- [x] errors
- [x] flash-messages
- [x] hello-world
- [x] multipart
- [x] negotiation
- [x] stream-file
- [x] stream-objects
- [x] stream-server-side-events
- [x] stream-view
- [x] templates
- [x] upload
- [x] vhost

**Comment by alnero** [comment]
Multipart Example
https://github.com/bananaappletw/koa2-examples/pull/3

I would like to migrate the rest of missing examples.

**Comment by alnero** [comment]
Negotiation Example
https://github.com/bananaappletw/koa2-examples/pull/4

**Comment by bananaappletw** [comment]
@alnero Thank you so much.
Actually, I plan to do that.
But I am busy with my school things in recent days.
I will check them when I am available.
Thank you.

**Comment by alnero** [comment]
Stream-objects Example
https://github.com/bananaappletw/koa2-examples/pull/5

**Comment by alnero** [comment]
Stream-server-side-events Example
https://github.com/bananaappletw/koa2-examples/pull/6

**Comment by alnero** [comment]
Upload Example
https://github.com/bananaappletw/koa2-examples/pull/7

**Comment by alnero** [comment]
Vhost Example
https://github.com/bananaappletw/koa2-examples/pull/8

**Comment by bananaappletw** [comment]
Thanks for the help from @alnero 
The whole examples are migrated to `koa2`.
