### ISSUE TITLE
Could you move stream-view example?

### ISSUE THREAD

**Issue by budarin** [bananaappletw/koa2-examples#2]
Help me please with stream-view example from previous version

**Comment by bananaappletw** [comment]
@budarin 
Sure.
I will migrate that soon.
After I migrated it, I will comment to let you know.
Thank you.

**Comment by bananaappletw** [comment]
@budarin 
Available here: https://github.com/bananaappletw/koa2-examples/tree/master/stream-view

**Comment by budarin** [comment]
thanks!
but this code is based on a generator version of koa
I look for async/await realization of the View

**Comment by bananaappletw** [comment]
@budarin 
I see.
I will try to change it.
If I done, I will inform you.
Thanks.

**Comment by bananaappletw** [comment]
@budarin I modify the view using `async` function now.

**Comment by budarin** [comment]
Thanks a lot!!
